server:
  port: 8094

spring:
  application:
    name: pay-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.144.132:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.144.132:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.144.132
      port: 6379
      password: 147258369
  config:
    import: classpath:application-alipay.yml
#  web:
#    resources:
#      static-locations:
#        - classpath:/META-INF/resources/
#        - classpath:/resources/
#        - classpath:/static/
#        - classpath:/public/
#  mvc:
#    static-path-pattern: /**