server:
  port: 8501
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.144.132:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      url: redis://147258369@192.168.144.132:6379
mybatis:
  mapper-locations: classpath:/com/lingfenglong/spzx/model/entity/*/*.xml
  config-location: classpath:/mybatis-config.xml
logging:
  level:
    web: trace

spzx:
  auth:
    no-auth-url:
      - /doc.html
      - /doc.html#/**
      - /webjars/**
      - /v3/**
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode