server:
  port: 8501
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.144.132:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      url: redis://147258369@192.168.144.132:6379
  servlet:
    multipart:
      max-file-size: 100MB

#mybatis:
#  mapper-locations: classpath:/com/lingfenglong/spzx/model/entity/*/*.xml
#  config-location: classpath:/mybatis-config.xml
#  type-aliases-package: com.lingfenglong.spzx.model.entity

logging:
  level:
    web: trace
    sql: trace

spzx:
  auth:
    no-auth-url:
      - /doc.html
      - /doc.html#/**
      - /webjars/**
      - /v3/**
      - /favicon.ico
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
  minio:
    endpoint: http://192.168.144.132:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: spzx-bucket
    allowed-content-type:
      "[image/png]": png
      "[image/jpeg]": jpg
      "[image/gif]": gif

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:/com/lingfenglong/spzx/model/entity/*/*.xml
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.lingfenglong.spzx.model.entity