server:
  port: 8090

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.144.132:8848
  data:
    redis:
      url: redis://147258369@192.168.144.132:6379
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.144.132:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456



mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
#  mapper-locations: classpath:/com/lingfenglong/spzx/model/entity/*/*.xml
#  config-location: classpath:/mybatis-config.xml
#  type-aliases-package: com.lingfenglong.spzx.model.entity
logging:
  level:
    com.lingfenglong.spzx.service.user.service.impl: debug
